name: 📝 Content Task
description: Plan or update written content such as blog posts, translations, or metadata.
title: '[Content] '
labels: [translation, documentation, content]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 📝 Content Task
        Use this template to propose or track a content-related task (blog entry, translation, static text, etc.).

  - type: textarea
    id: content-area
    attributes:
      label: Area or section
      description: Which part of the project does this apply to?
      placeholder: e.g. Blog post, About page, Footer links, etc.
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: Describe the content task
      description: Be specific about what needs to be written, translated, corrected, or updated.
      placeholder: e.g. Write Spanish version of “Welcome to WoodBench” blog post.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Extra notes (optional)
      description: Add any links, references, or related tasks if needed.
      placeholder: Optional notes...
